controllers:
    resource: ../src/Controller/
    type: annotation

app_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'home.html.twig'
kernel:
    resource: ../src/Kernel.php
    type: annotation

app_login:
    path: /connexion
    controller: App\Controller\SecurityController::login
